### PR TITLE
Isaac forgot password

### PR DESCRIPTION
**Pull request by PressedPink**
- Forgot password logic
- Forgot password views
- Forgot password HTML/CSS
- Backend emailing

### CODE REVIEW

**Comment by alexMFuller** [comment]
Good to merge

**Review by alexMFuller — APPROVED** [review]
approved!

**Comment by alexMFuller** [comment]
I will resolve conflicts when ready to merge if needed

**Review by ConnorNethen — APPROVED** [review]
Looks great

**Pull request merged**
